// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace FreeChat.Web.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddMainCategoriesFluentConfiguration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMainCategoriesFluentConfiguration));
        
        string IMigrationMetadata.Id
        {
            get { return "201804111351438_AddMainCategoriesFluentConfiguration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
