// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace FreeChat.Web.Migrations
{
    //[GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")] 
    public sealed partial class AddingDomainModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingDomainModels));

        string IMigrationMetadata.Id
        {
            get { return "201801031026586_AddingDomainModels"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
